version: '2'
services:
  product-server:
    container_name: ams-backend
    build:
      dockerfile: Dockerfile
    image: jestercharles/ams-backend:1.0.0
    ports:
      - 8081:8080
    environment:
      - postgresPass=${postgresPass}
